const PortfolioProjects = [
  {
    id: 0,
    imageMobile: "/portfolio/mobile/image-portfolio-fylo@2x.jpg",
    imageTablet: "/portfolio/tablet/image-portfolio-fylo@2x.jpg",
    imageDesktop: "/portfolio/desktop/image-portfolio-clock@2x.jpg",
    title: "Bitcoin Clock",
    slug: "clock",
    introduction:
      "This project is a responsive Bitcoin Clock app built with NextJS. It uses the FetchAPI to call Bitcoin Price Feed and Time from external APIs and integrates Satoshi Nakamoto's quotes from our own firebase database. Here I experimented with some animations for smooth transitions using Framermotion",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It's a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I've learned something new with each project, helping me to improve and adapt my style.",
    category: "Interaction Design / Front End Development",
    languages: "NextJS / TailwindCSS / Framermotion / Firebase",
    heroMobile: "/detail/mobile/image-fylo-hero@2x.jpg",
    heroTablet: "/detail/tablet/image-fylo-hero@2x.jpg",
    heroDesktop: "/detail/desktop/image-fylo-hero@2x.jpg",
    previewMobile: "/detail/mobile/image-fylo-preview-1@2x.jpg",
    preview2Mobile: "/detail/mobile/image-fylo-preview-2@2x.jpg",
    previewTablet: "/detail/tablet/image-fylo-preview-1@2x.jpg",
    preview2Tablet: "/detail/tablet/image-fylo-preview-2@2x.jpg",
    previewDesktop: "/detail/desktop/image-fylo-preview-1@2x.jpg",
    preview2Desktop: "/detail/desktop/image-fylo-preview-2@2x.jpg",
    website: "https://fem-bitcoin-clock.vercel.app",
  },
  {
    id: 1,
    imageMobile: "/portfolio/mobile/image-portfolio-manage@2x.jpg",
    imageTablet: "/portfolio/tablet/image-portfolio-manage@2x.jpg",
    imageDesktop: "/portfolio/desktop/image-portfolio-manage@2x.jpg",
    title: "Manage",
    slug: "manage",
    introduction:
      "This project required me to build a fully responsive landing page to the designs provided. I used HTML5, along with CSS Grid and JavaScript for the areas that required interactivity, such as the testimonial slider.",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It's a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I've learned something new with each project, helping me to improve and adapt my style.",
    category: "Interaction Design / Front End Development",
    languages: "HTML / CSS / JS",
    heroMobile: "/detail/mobile/image-manage-hero@2x.jpg",
    heroTablet: "/detail/tablet/image-manage-hero@2x.jpg",
    heroDesktop: "/detail/desktop/image-manage-hero@2x.jpg",
    previewMobile: "/detail/mobile/image-manage-preview-1@2x.jpg",
    preview2Mobile: "/detail/mobile/image-manage-preview-2@2x.jpg",
    previewTablet: "/detail/tablet/image-manage-preview-1@2x.jpg",
    preview2Tablet: "/detail/tablet/image-manage-preview-2@2x.jpg",
    previewDesktop: "/detail/desktop/image-manage-preview-1@2x.jpg",
    preview2Desktop: "/detail/desktop/image-manage-preview-2@2x.jpg",
    website:
      "https://www.frontendmentor.io/challenges/manage-landing-page-SLXqC6P5",
  },
  {
    id: 2,
    imageMobile: "/portfolio/mobile/image-portfolio-bookmark@2x.jpg",
    imageTablet: "/portfolio/tablet/image-portfolio-bookmark@2x.jpg",
    imageDesktop: "/portfolio/desktop/image-portfolio-bookmark@2x.jpg",
    title: "Bookmark",
    slug: "bookmark",
    introduction:
      "This project required me to build a fully responsive landing page to the designs provided. I used HTML5, along with CSS Grid and JavaScript for the areas that required interactivity, such as the features section.",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It's a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I've learned something new with each project, helping me to improve and adapt my style.",
    category: "Interaction Design / Front End Development",
    languages: "HTML / CSS / JS",
    heroMobile: "/detail/mobile/image-bookmark-hero@2x.jpg",
    heroTablet: "/detail/tablet/image-bookmark-hero@2x.jpg",
    heroDesktop: "/detail/desktop/image-bookmark-hero@2x.jpg",
    previewMobile: "/detail/mobile/image-bookmark-preview-1@2x.jpg",
    preview2Mobile: "/detail/mobile/image-bookmark-preview-2@2x.jpg",
    previewTablet: "/detail/tablet/image-bookmark-preview-1@2x.jpg",
    preview2Tablet: "/detail/tablet/image-bookmark-preview-2@2x.jpg",
    previewDesktop: "/detail/desktop/image-bookmark-preview-1@2x.jpg",
    preview2Desktop: "/detail/desktop/image-bookmark-preview-2@2x.jpg",
    website:
      "https://www.frontendmentor.io/challenges/bookmark-landing-page-5d0b588a9edda32581d29158",
  },
  {
    id: 3,
    imageMobile: "/portfolio/mobile/image-portfolio-insure@2x.jpg",
    imageTablet: "/portfolio/tablet/image-portfolio-insure@2x.jpg",
    imageDesktop: "/portfolio/desktop/image-portfolio-insure@2x.jpg",
    title: "Insure",
    slug: "insure",
    introduction:
      "This was a small project which mostly consisted of HTML and CSS. I built a fully-responsive landing page. The only JavaScript this project required was to enable the toggling of the mobile navigation.",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It's a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I've learned something new with each project, helping me to improve and adapt my style.",
    category: "Interaction Design / Front End Development",
    languages: "HTML / CSS / JS",
    heroMobile: "/detail/mobile/image-insure-hero@2x.jpg",
    heroTablet: "/detail/tablet/image-insure-hero@2x.jpg",
    heroDesktop: "/detail/desktop/image-insure-hero@2x.jpg",
    previewMobile: "/detail/mobile/image-insure-preview-1@2x.jpg",
    preview2Mobile: "/detail/mobile/image-insure-preview-2@2x.jpg",
    previewTablet: "/detail/tablet/image-insure-preview-1@2x.jpg",
    preview2Tablet: "/detail/tablet/image-insure-preview-2@2x.jpg",
    previewDesktop: "/detail/desktop/image-insure-preview-1@2x.jpg",
    preview2Desktop: "/detail/desktop/image-insure-preview-2@2x.jpg",
    website:
      "https://www.frontendmentor.io/challenges/insure-landing-page-uTU68JV8",
  },
  {
    id: 4,
    imageMobile: "/portfolio/mobile/image-portfolio-fylo@2x.jpg",
    imageTablet: "/portfolio/tablet/image-portfolio-fylo@2x.jpg",
    imageDesktop: "/portfolio/desktop/image-portfolio-fylo@2x.jpg",
    title: "Fylo",
    slug: "fylo",
    introduction:
      "This project was built in pure HTML and CSS. I had mobile and desktop designs to work to and built it so that it was fully-responsive. I took a mobile-first approach and used modern CSS like Flexbox and Grid for layout purposes.",
    background:
      "This project was a front-end  challenge from Frontend Mentor. It's a platform that enables you to practice building websites to a design and project brief. Each challenge includes mobile and desktop designs to show how the website should look at different screen sizes. Creating these projects has helped me refine my workflow and solve real-world coding problems. I've learned something new with each project, helping me to improve and adapt my style.",
    category: "Interaction Design / Front End Development",
    languages: "HTML / CSS",
    heroMobile: "/detail/mobile/image-fylo-hero@2x.jpg",
    heroTablet: "/detail/tablet/image-fylo-hero@2x.jpg",
    heroDesktop: "/detail/desktop/image-fylo-hero@2x.jpg",
    previewMobile: "/detail/mobile/image-fylo-preview-1@2x.jpg",
    preview2Mobile: "/detail/mobile/image-fylo-preview-2@2x.jpg",
    previewTablet: "/detail/tablet/image-fylo-preview-1@2x.jpg",
    preview2Tablet: "/detail/tablet/image-fylo-preview-2@2x.jpg",
    previewDesktop: "/detail/desktop/image-fylo-preview-1@2x.jpg",
    preview2Desktop: "/detail/desktop/image-fylo-preview-2@2x.jpg",
    website:
      "https://www.frontendmentor.io/challenges/fylo-dark-theme-landing-page-5ca5f2d21e82137ec91a50fd",
  },
];

export default PortfolioProjects;
