import Head from "next/head";
import ButtonPrimary from "../components/ButtonPrimary";
import ButtonSecondary from "../components/ButtonSecondary";
import ContactFooter from "../components/ContactFooter";
import Footer from "../components/Footer";
import Header from "../components/Header";
// import TypeWriter from "react-typewriter";
import Link from "next/link";

export default function Home() {
  return (
    <div className='flex min-h-screen flex-col justify-between'>
      <Head>
        <title>Minimalist Portfolio Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='theme-color' content='#fafafa' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <Header />

      <main className='mt-[104px] bg-secondary_grey_bg px-8 sm:mt-[144px] sm:px-10 xl:mx-auto xl:max-w-[1440px] xl:px-[165px]'>
        <img
          src='/homepage/mobile/image-homepage-hero@2x.jpg'
          alt=''
          className='mb-6 sm:hidden'
        />
        <div className='relative h-auto w-auto'>
          <img
            src='/homepage/tablet/image-homepage-hero@2x.jpg'
            alt=''
            className='hidden sm:mb-0 sm:inline-block xl:hidden'
          />
          <img
            src='/homepage/desktop/image-homepage-hero@2x.jpg'
            alt=''
            className='hidden xl:mb-0 xl:inline-block'
          />
          <div className='sm:absolute sm:bottom-0 sm:flex sm:h-[278px] sm:w-[514px] sm:flex-col sm:justify-end sm:bg-secondary_grey_bg xl:h-[357px] xl:w-[445px]'>
            {/* <TypeWriter typing={1.5} fixed={true}> */}
            <h1 className='mb-8 hidden xl:inline-block xl:w-[390px]'>
              Hey, I'm Peter,
              <br /> <span className='italic'>an architect, </span> turned
              front-end developer.
            </h1>
            {/* </TypeWriter> */}
            {/* <TypeWriter typing={1.5} fixed={true}> */}
            <h2 className='mb-8 sm:w-[458px] xl:hidden'>
              Hey, I'm Peter,
              <br /> <span className='italic'>an architect, </span> turned
              front-end developer.
            </h2>
            {/* </TypeWriter> */}
            <ButtonPrimary href='#about-me-section'>ABOUT ME</ButtonPrimary>
          </div>
        </div>

        <div className='mb-8 mt-24 sm:mb-0 sm:grid sm:grid-cols-10 xl:mt-[150px] xl:flex'>
          <img
            src='/homepage/mobile/image-homepage-profile@2x.jpg'
            alt=''
            className='sm:hidden'
          />
          <img
            src='/homepage/tablet/image-homepage-profile@2x.jpg'
            alt=''
            className='hidden sm:col-span-4 sm:inline-block xl:hidden'
          />
          <img
            src='/homepage/desktop/image-homepage-profile@2x.jpg'
            alt=''
            className='hidden xl:inline-block xl:w-[540px] xl:flex-initial'
          />
          <div className='hidden xl:inline-block xl:w-[125px] xl:flex-initial'></div>
          <div className='sm:col-span-6 sm:flex sm:flex-col sm:justify-between sm:pl-[68px] xl:w-[350px] xl:flex-initial xl:pl-0'>
            <div id='about-me-section'>
              <hr className='hidden sm:flex' />
              <div>
                <h2 className='mb-7 mt-8'>About Me</h2>
                <p className='mb-6'>
                  I'm a front-end developer looking for a new role in an
                  exciting bitcoin-related company. I focus on writing
                  accessible HTML/CSS and clean JavaScript with modern
                  frameworks such as React/NextJS. I'm based in Sydney, Aus but
                  happy working remotely. I spent my early career in
                  architecture, where I was project lead for a tennis{" "}
                  <Link href='https://www.coxarchitecture.com.au/perspective/game-set-match-ken-rosewall-arena-announced-a-winner-at-the-world-architecture-festival/'>
                    <a className='underline'> stadium</a>
                  </Link>{" "}
                  . After falling down the Bitcoin Standard, Sovereign
                  Individual rabbit-hole in 2021, I've pivoted to tech to
                  contribute to the growing open-financial system enabled by
                  Bitcoin. I'd love you to check out my work.
                </p>

                <ButtonSecondary href='/portfolio'>
                  GO TO PORTFOLIO
                </ButtonSecondary>
              </div>
            </div>
            <hr className='hidden sm:inline-block' />
          </div>
        </div>

        <hr className='mt-[50px] mb-[35px] sm:hidden' />

        <ContactFooter />
      </main>
      <Footer />
    </div>
  );
}
